local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

ls.add_snippets("typescript", {
	s("effs", {
		i(1, "loadItems"),
		t("$ = createEffect(() =>"),
		t({ "", "\tthis.actions$.pipe(" }),
		t({ "", "\t\tofType(" }),
		i(2, "ItemsActions.loadItems"),
		t("),"),
		t({ "", "\t\tswitchMap(() =>" }),
		t({ "", "\t\t\tthis." }),
		i(3, "itemsService"),
		t("."),
		i(4, "loadItems"),
		t("().pipe("),
		t({ "", "\t\t\t\tmap((" }),
		i(5, "items"),
		t(") => "),
		i(6, "ItemsActions.loadItemsSuccess"),
		t("({ "),
		i(7, "items"),
		t(" })),"),

		t({ "", "\t\t\t\tcatchError((" }),
		i(8, "error"),
		t(") => of("),
		i(9, "ItemsActions.loadItemsFailure"),
		t("({ "),
		i(10, "error"),
		t(" })))"),

		t({ "", "\t\t\t))" }),
		t({ "", "\t\t)" }),
		t({ "", "\t)" }),
		t({ "", ");" }),
	}),

	s("effm", {
		i(1, "saveItem"),
		t("$ = createEffect(() =>"),
		t({ "", "\tthis.actions$.pipe(" }),
		t({ "", "\t\tofType(" }),
		i(2, "ItemsActions.saveItem"),
		t("),"),
		t({ "", "\t\tmergeMap((action) =>" }),
		t({ "", "\t\t\tthis." }),
		i(3, "itemsService"),
		t("."),
		i(4, "saveItem"),
		t("(action."),
		i(5, "item"),
		t(").pipe("),
		t({ "", "\t\t\t\tmap((" }),
		i(6, "item"),
		t(") => "),
		i(7, "ItemsActions.saveItemSuccess"),
		t("({ "),
		i(8, "item"),
		t(" })),"),

		t({ "", "\t\t\t\tcatchError((" }),
		i(9, "error"),
		t(") => of("),
		i(10, "ItemsActions.saveItemFailure"),
		t("({ "),
		i(11, "error"),
		t(" })))"),

		t({ "", "\t\t\t))" }),
		t({ "", "\t\t)" }),
		t({ "", "\t)" }),
		t({ "", ");" }),
	}),

	s("effc", {
		i(1, "updateItem"),
		t("$ = createEffect(() =>"),
		t({ "", "\tthis.actions$.pipe(" }),
		t({ "", "\t\tofType(" }),
		i(2, "ItemsActions.updateItem"),
		t("),"),
		t({ "", "\t\tconcatMap((action) =>" }),
		t({ "", "\t\t\tthis." }),
		i(3, "itemsService"),
		t("."),
		i(4, "updateItem"),
		t("(action."),
		i(5, "item"),
		t(").pipe("),
		t({ "", "\t\t\t\tmap((" }),
		i(6, "item"),
		t(") => "),
		i(7, "ItemsActions.updateItemSuccess"),
		t("({ "),
		i(8, "item"),
		t(" })),"),

		t({ "", "\t\t\t\tcatchError((" }),
		i(9, "error"),
		t(") => of("),
		i(10, "ItemsActions.updateItemFailure"),
		t("({ "),
		i(11, "error"),
		t(" })))"),

		t({ "", "\t\t\t))" }),
		t({ "", "\t\t)" }),
		t({ "", "\t)" }),
		t({ "", ");" }),
	}),

	s("effx", {
		i(1, "submitForm"),
		t("$ = createEffect(() =>"),
		t({ "", "\tthis.actions$.pipe(" }),
		t({ "", "\t\tofType(" }),
		i(2, "FormActions.submitForm"),
		t("),"),
		t({ "", "\t\texhaustMap((action) =>" }),
		t({ "", "\t\t\tthis." }),
		i(3, "formService"),
		t("."),
		i(4, "submitForm"),
		t("(action."),
		i(5, "payload"),
		t(").pipe("),
		t({ "", "\t\t\t\tmap((response) => " }),
		i(6, "FormActions.submitFormSuccess"),
		t("({ response })),"),

		t({ "", "\t\t\t\tcatchError((error) => of(" }),
		i(7, "FormActions.submitFormFailure"),
		t("({ error })))"),

		t({ "", "\t\t\t))" }),
		t({ "", "\t\t)" }),
		t({ "", "\t)" }),
		t({ "", ");" }),
	}),

	s("effn", {
		i(1, "redirectAfterSave"),
		t("$ = createEffect("),
		t({ "", "\t() =>" }),
		t({ "", "\t\tthis.actions$.pipe(" }),
		t({ "", "\t\t\tofType(" }),
		i(2, "ItemsActions.saveItemSuccess"),
		t("),"),
		t({ "", "\t\t\ttap(() => {" }),
		t({ "", "\t\t\t\t" }),
		i(3, "this.router.navigate(['/items'])"),
		t({ "", "\t\t\t})" }),
		t({ "", "\t\t)," }),
		t({ "", "\t{ dispatch: false }" }),
		t({ "", ");" }),
	}),
})
